//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Undefined.Serialization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Undefined.Serialization.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot represent {0} as attribute value. 的本地化字符串。
        /// </summary>
        internal static string CannotSerializeAsAttribute {
            get {
                return ResourceManager.GetString("CannotSerializeAsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A circular reference of {0} has been detected. 的本地化字符串。
        /// </summary>
        internal static string CircularReferenceDetected {
            get {
                return ResourceManager.GetString("CircularReferenceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add item to {0} . 的本地化字符串。
        /// </summary>
        internal static string CollectionCannotAddItem {
            get {
                return ResourceManager.GetString("CollectionCannotAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot serialize {0} as an element in collection type. 的本地化字符串。
        /// </summary>
        internal static string CollectionPropertyElementNotSupported {
            get {
                return ResourceManager.GetString("CollectionPropertyElementNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified XDocument has no root element. 的本地化字符串。
        /// </summary>
        internal static string EmptyXDocument {
            get {
                return ResourceManager.GetString("EmptyXDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In situ deserialization is not supported for member {0} with value {1}. 的本地化字符串。
        /// </summary>
        internal static string InSituDeserializationNotSupported {
            get {
                return ResourceManager.GetString("InSituDeserializationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid attributes combination: {0}. 的本地化字符串。
        /// </summary>
        internal static string InvalidAttributesCombination {
            get {
                return ResourceManager.GetString("InvalidAttributesCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot cast {0} to {1}. 的本地化字符串。
        /// </summary>
        internal static string InvalidObjectType {
            get {
                return ResourceManager.GetString("InvalidObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot deserialize readonly structure. 的本地化字符串。
        /// </summary>
        internal static string StrcutureReadonly {
            get {
                return ResourceManager.GetString("StrcutureReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot deserialize {0}。 的本地化字符串。
        /// </summary>
        internal static string UnableToDeserialize {
            get {
                return ResourceManager.GetString("UnableToDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} has not been registered in scope: {0}. 的本地化字符串。
        /// </summary>
        internal static string UnregisteredType {
            get {
                return ResourceManager.GetString("UnregisteredType", resourceCulture);
            }
        }
    }
}
